#!/bin/bash

# Requirements are set
## Python
python_is_here=$(python3 --version)
if [[ -z "$python_is_here" ]]
then
    echo "Python3 is not installed! Please check https://www.python.org/downloads/"
    exit 1
else
    echo "Python 3 already installed !"
fi

## Poetry
poetry_is_here=$(poetry --version)
if [[ -z "$poetry_is_here" ]]
then
    echo "Poetry not installed. Launching installation..."
    curl -sSL https://install.python-poetry.org | python3 -
    echo "Poetry installed !"
else
    echo "Poetry already installed !"
fi

# Project informations
## Project name
while [[ -z "$project_name" ]]; do
    echo "Give the name of your project in snake_case: "
    read project_name
done
sed -i "s/PROJECT_NAME/$project_name/g" pyproject.toml
sed -i "s/python_app/$project_name/g" README.md
mv python_app/ "$project_name"

## Project description
while [[ -z "$description" ]]; do
    echo "Give the description of your project: "
    read description
done
sed -i "s/DESCRIPTION/$description/g" pyproject.toml

## Project information in pyproject.toml
### Name of the developer
name="dev"
echo "Give your name (default: $name): "
read name
sed -i "s/NAME/$name/" pyproject.toml

### Email of the developer
email="contact@opensourcepolitics.eu"
echo "Give your e-mail (default: $email): "
read email
sed -i "s/EMAIL/$email/" pyproject.toml

# Setup environment
poetry install
poetry shell